# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 41c81cd1359483b2a5b745add7cf557ba92057fb926019a9abbddcf36f397587b6d568a3d1c3d9d60b1528c08022a17de5d1d4d1a61bb57777306ac3b528e5fc

test:
  secret_key_base: 50dd233fb192c6b9f4600b2a98847bbbd05d00b70cb4f9f1eb3158eef91c9c30a9d0dbe2f1a78372a37726b95b17fdb807dfabf6f94710ba49024363fdaffdf3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
